### ISSUE TITLE
环境变量名称错误

### ISSUE THREAD

**Issue by zhangyoufu** [aliyun/credentials-go#37]
README 中给出的环境变量名称是 `ALICLOUD_ACCESS_KEY` 和 `ALICLOUD_SECRET_KEY`

代码中使用的是 `ALIBABA_CLOUD_ACCESS_KEY_Id` 和 `ALIBABA_CLOUD_ACCESS_KEY_SECRET`

https://github.com/aliyun/credentials-go/blob/be5676a98bcd62c74d5ce65e33ad8a9cdb22ba76/credentials/env_provider.go#L14-L19

代码和文档不匹配。

另外 `Id` 这个大小写非常奇葩。Linux 系统下环境变量大小写敏感，容易造成问题，建议统一使用大写字母。

**Comment by zhangyoufu** [comment]
建议把环境变量这部分逻辑和 `aliyun-cli` 保持一致，参考 https://github.com/aliyun/aliyun-cli#support-for-environment-variables

**Comment by yndu13** [comment]
已经在 https://github.com/aliyun/credentials-go/commit/687bfa3dee13b9a2c9b6fdefef02ba68e3a0c191 解决
